version: '2'

services:
    zk1:
        image: okdokey/zookeeper:3.4.14
        container_name: zk1
        hostname: zk1
        networks:
            hadoop:
                aliases:
                  - zk1
        ports:
            - 2181:2181
        environment:
            ZK_MY_ID: 1
            ZK_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888

    zk2:
        image: okdokey/zookeeper:3.4.14
        container_name: zk2
        hostname: zk2
        networks:
            hadoop:
                aliases:
                  - zk2
        ports:
            - 2182:2181
        environment:
            ZK_MY_ID: 2
            ZK_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888

    zk3:
        image: okdokey/zookeeper:3.4.14
        container_name: zk3
        hostname: zk3
        networks:
            hadoop:
                aliases:
                  - zk3
        ports:
            - 2183:2181
        environment:
            ZK_MY_ID: 3
            ZK_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888
networks:
  hadoop: