version: '2'

services:
    zoo1:
        image: zookeeper:latest
        container_name: zoo1
        hostname: zoo1
        networks:
            hadoop:
                aliases:
                  - zoo1
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo2:
        image: zookeeper:latest
        container_name: zoo2
        hostname: zoo2
        networks:
            hadoop:
                aliases:
                  - zoo2
        ports:
            - 2182:2181
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo3:
        image: zookeeper:latest
        container_name: zoo3
        hostname: zoo3
        networks:
            hadoop:
                aliases:
                  - zoo3
        ports:
            - 2183:2181
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
networks:
  hadoop: